name:  Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Greet me
        run: echo "welcome to github actions"

      - name: Node & NPM versions
        run: |
          node -v
          npm -v