name: Decrypt with gpg
on:
  push:
jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.4.0
        
      - name: decrypt secret file
        run: |
          ls -a
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret-key.txt secret-key.txt.gpg
        env: 
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: print secret-key file content
        run: cat $HOME/secret-key.txt